name = "Marguerite"
uuid = "7cfbf62e-f66e-40cd-83d7-4baf4195a571"
authors = ["samtalki <saimouer@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
