using Marguerite
using Documenter

DocMeta.setdocmeta!(Marguerite, :DocTestSetup, :(using Marguerite); recursive=true)

site_build = get(ENV, "SITE_BUILD", "false") == "true"

format_opts = if site_build
    # Build for personal website: pretty URLs, canonical link, no edit links
    Documenter.HTML(
        prettyurls = true,
        canonical = "https://samueltalkington.com/research/marguerite/",
        edit_link = nothing,
    )
else
    # Default: local or CI build
    Documenter.HTML(;
        prettyurls = get(ENV, "CI", nothing) == "true",
        edit_link="main",
        assets=String[],
    )
end

makedocs(;
    modules=[Marguerite],
    warnonly=[:missing_docs],
    authors="samtalki <saimouer@gmail.com> and contributors",
    sitename="Marguerite.jl",
    format=format_opts,
    pages=[
        "Home" => "index.md",
        "Tutorial" => "tutorial.md",
        "Oracles" => "oracles.md",
        "Differentiation" => "differentiation.md",
        "API Reference" => "api.md",
    ],
)

if site_build
    # Stub siteinfo.js — normally generated by deploydocs(), which we skip.
    # Prevents a 404 when Documenter's JS requests it.
    write(joinpath(@__DIR__, "build", "siteinfo.js"),
        """var DOCUMENTER_CURRENT_VERSION = "dev";""")
else
    deploydocs(;
        repo="github.com/samtalki/Marguerite.jl",
        devbranch="main",
    )
end
