# Copyright 2026 Samuel Talkington
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

using Marguerite
import ChainRulesCore
using Documenter

DocMeta.setdocmeta!(Marguerite, :DocTestSetup, :(using Marguerite); recursive=true)

site_build = get(ENV, "SITE_BUILD", "false") == "true"

assets = ["assets/custom.css", "assets/theme-default.js"]

format_opts = if site_build
    # Build for personal website: pretty URLs, canonical link, no edit links
    Documenter.HTML(;
        prettyurls = true,
        canonical = "https://samueltalkington.com/research/marguerite/",
        edit_link = nothing,
        assets = assets,
    )
else
    # Default: local or CI build
    Documenter.HTML(;
        prettyurls = get(ENV, "CI", nothing) == "true",
        edit_link="main",
        assets = assets,
    )
end

makedocs(;
    modules=[Marguerite],
    warnonly=[:missing_docs, :cross_references],
    authors="samtalki <10187005+samtalki@users.noreply.github.com> and contributors",
    sitename="Marguerite.jl",
    format=format_opts,
    pages=[
        "Home" => "index.md",
        "Tutorial" => "tutorial.md",
        "Oracles" => "oracles.md",
        "Parametric Oracles" => "parametric_oracles.md",
        "Examples" => [
            "Sparse Recovery" => "examples.md",
            "Graph Problems" => "graphs.md",
            "SDP Relaxation" => "sdp.md",
        ],
        "Convergence" => "convergence.md",
        "Differentiation" => "differentiation.md",
        "Bilevel Optimization" => "bilevel.md",
        "Batched Solving" => "batching.md",
        "API Reference" => "api.md",
    ],
)

if site_build
    # Stub siteinfo.js — normally generated by deploydocs(), which we skip.
    # Prevents a 404 when Documenter's JS requests it.
    write(joinpath(@__DIR__, "build", "siteinfo.js"),
        """var DOCUMENTER_CURRENT_VERSION = "dev";""")
end
